"""Schéma colonnes attendues des CSV du sujet CISIA Santé."""

from __future__ import annotations

SCHEMA_ATTENDU: dict[str, list[str]] = {
    "patients.csv": [
        "PatientID",
        "NomPrenom",
        "DateNaissance",
        "Sexe",
        "CodePostal",
        "Commune",
        "RegimeAssurance",
        "MedecinTraitant",
        "PersonneAPrevenir",
        "SituationFamiliale",
        "PathologiesChroniques",
    ],
    "sejours.csv": [
        "SejourID",
        "PatientID",
        "DateAdmission",
        "DateSortie",
        "DureeSejour",
        "Service",
        "TypeSejour",
        "GHM",
        "ModeSortie",
        "Readmission30j",
    ],
    "historique.csv": [
        "EvenementID",
        "PatientID",
        "TypeEvenement",
        "DateEvenement",
        "DureeJours",
        "CodeEtablissement",
    ],
    "diagnostics.csv": [
        "DiagnosticID",
        "SejourID",
        "CodeCIM10",
        "LibelleDiagnostic",
        "Role",
    ],
    "actes.csv": [
        "ActeID",
        "SejourID",
        "CodeCCAM",
        "LibelleActe",
        "DateActe",
        "CodeExecutant",
    ],
    "biologies.csv": [
        "BiologieID",
        "SejourID",
        "DatePrelevement",
        "Panel",
        "Valeur",
        "Unite",
        "ValeurReferenceBas",
        "ValeurReferenceHaut",
    ],
    "signes_vitaux.csv": [
        "ConstanteID",
        "SejourID",
        "Horodatage",
        "FrequenceCardiaque",
        "TensionSystolique",
        "TensionDiastolique",
        "Temperature",
        "FrequenceRespiratoire",
        "SpO2",
    ],
    "medications.csv": [
        "PrescriptionID",
        "PatientID",
        "SejourID",
        "CodeATC",
        "LibelleMedicament",
        "Posologie",
        "DateDebut",
        "DateFin",
        "Voie",
    ],
    "comptes_rendus.csv": [
        "CompteRenduID",
        "SejourID",
        "TypeCR",
        "DateCR",
        "TexteCR",
    ],
    "objets_connectes.csv": [
        "MesureID",
        "PatientID",
        "Horodatage",
        "TypeMesure",
        "Valeur",
        "QualiteSignal",
    ],
    "territoire_insee.csv": [
        "Commune",
        "CodePostal",
        "IndiceDefavorisation",
        "DensiteMedicale",
        "PopulationCommune",
    ],
}

FEATURES_CLES = (
    "SejourID",
    "PatientID",
    "split",
    "Readmission30j",
)
